#################################################
# xl apply -f deploy.yaml --values version=2.0.0
#################################################
---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Applications/tutorial
  type: udm.Application
- name: !format Applications/tutorial/%version%
  type: udm.DeploymentPackage
  deployables:
  - name: chart
    type: helm.Chart
    chartName: bitnami/tomcat
    chartVersion: 6.3.11
    inputVariables:
      hostAliases: "{{ hostAliases }}"
      appVersion: 1.0.0
    secretInputVariables:
      tomcatPassword: "{{ tomcatPassword }}"