#################################################
# xl apply -f deploy.yaml --values version=2.0.0
#################################################
---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: !format Applications/tutorial-helm/%version%
  type: udm.DeploymentPackage
  satisfiesOkTestManager: true
  satisfiesOkReleaseManager: true
  deployables:
  - name: tutorial-helm
    type: helm.Chart
    chartName: bitnami/tomcat
    chartVersion: 6.3.11
    inputVariables:
      hostAliases: "{{ hostAliases }}"
      appVersion: 1.0.0
    secretInputVariables:
      tomcatPassword: "{{ tomcatPassword }}"