#####################################################
# xl apply -f deploy.yaml --values version=1.0.0-B1
#####################################################
---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: !format Applications/Applications/application-tutorial/tutorial-k8s/%version%
  type: udm.DeploymentPackage
  deployables:
  - name: tutorial
    type: uccm.ContainerSpec
    image: !format lyhsoft/tutorial:%version%
    replicas: "{{ replicas }}"
    profile: production
    ports:
    - name: port
      type: uccm.ContainerPortSpec
      containerPort: 1234
      servicePort: 80
      exposeAsIngress: true