#################################################
# xl apply -f deploy.yaml --values version=2.0.0
#################################################
---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: !format Applications/Applications/application-tutorial/tutorial-k8s/%version%
  type: udm.DeploymentPackage
  deployables:
  - name: container
    type: uccm.ContainerSpec
    image: !format lyhsoft/tutorial:%version%
    replicas: "{{ replicas }}"
    env:
      connection-string: "{{ connection-string }}"
      user-bdd: "{{ user-bdd }}"
    securedEnv:
      password-bdd: "{{ password-bdd }}"
    ports:
    - name: port
      type: uccm.ContainerPortSpec
      containerPort: 1234
      servicePort: 80
      exposeAsIngress: true